[package]
name = "libhf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

# TODO: Dependencies per target
[dependencies]
